name = "cf" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.kang.cepu.us.kg"
custom_domain = true
