name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "frazier.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tronic.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.wt0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.t0p.topplug7.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.t0p.topplug7.us.kg"
custom_domain = true
